apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-simple-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python-simple-api
  template:
    metadata:
      labels:
        app: python-simple-api
    spec:
      containers:
      - name: python-simple-api
        image: nettooe/python-simple-api:1.1.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-simple-api
spec:
  selector:
    app: python-simple-api
  ports:
  - port: 80  
    targetPort: 8000

