apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-simple-api-homolog
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: python-simple-api-homolog
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/homolog
    repoURL: https://github.com/nettooe/python-simple-api.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true # sinaliza se deve eliminar o que existe

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-simple-api-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: python-simple-api-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/prod
    repoURL: https://github.com/nettooe/python-simple-api.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true # sinaliza se deve eliminar o que existe